server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false

#日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl